[package]
name = "incremental_mt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2 = "0.1.3"
anyhow = "1.0.72"
rand = "0.8.5"
log = "0.4.19"
defmt = "0.3.5"